// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID        uuid.UUID
	Owner     string
	Balance   decimal.Decimal
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Entry struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Amount    decimal.Decimal
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Transfer struct {
	ID            uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Amount        decimal.Decimal
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
