// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"time"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (
    username,
    hashed_password,
    full_name,
    email
) VALUES (
    $1,$2,$3,$4
) RETURNING username, hashed_password, full_name, email, password_changed_at, created_at, refresh_token
`

type CreateUsersParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	FullName       string `json:"full_name"`
	Email          string `json:"email"`
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.RefreshToken,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT username,full_name,email,username, hashed_password, full_name, email, password_changed_at, created_at, refresh_token FROM users
ORDER BY username
`

type GetAllUsersRow struct {
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	Username_2        string    `json:"username_2"`
	HashedPassword    string    `json:"hashed_password"`
	FullName_2        string    `json:"full_name_2"`
	Email_2           string    `json:"email_2"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	RefreshToken      string    `json:"refresh_token"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.Username_2,
			&i.HashedPassword,
			&i.FullName_2,
			&i.Email_2,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.RefreshToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT username, hashed_password, full_name, email, password_changed_at, created_at, refresh_token FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.RefreshToken,
	)
	return i, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE users
SET refresh_token = $2
WHERE username = $1
`

type UpdateRefreshTokenParams struct {
	Username     string `json:"username"`
	RefreshToken string `json:"refresh_token"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.Username, arg.RefreshToken)
	return err
}
